package Manager;

public enum Feedback {
    SUBTASK_SUCCESSFULLY_ADDED,
    SUBTASK_SUCCESSFULLY_UPDATED,
    TASK_SUCCESSFULLY_UPDATED,
    SUBTASK_SUCCESSFULLY_DELETED,

    UNABLE_TO_UPDATE_STATUS_FOR_EPIC_TASK,
    NON_EXISTING_TASK_ID,
    FAILED_TO_UPDATE_SUBTASK_NON_EXISTING_ID,
    FAILED_TO_DELETE_SUBTASK_NON_EXISTING_ID

}
