package Manager;

public enum Feedback {
    SUBTASK_SUCCESSFULLY_ADDED,
    SUBTASK_SUCCESSFULLY_UPDATED,
    TASK_SUCCESSFULLY_UPDATED,

    START_TIME_SUCCESSFULLY_UPDATED,

    NO_SUCH_SUBTASK_ID_FOR_TASK_GIVEN,
    SUBTASK_SUCCESSFULLY_DELETED,

    NO_SUBTASKS_TO_BE_RESCHEDULED_FOUND,
    NO_TASKS_TO_BE_RESCHEDULED_FOUND,

    DURATION_UPDATED,

    SUBTASKS_SCHEDULE_UPDATED,
    SUBTASKS_SUCCESSFULLY_DELETED,

    UNABLE_TO_CHANGE_DURATION_FOR_EPIC_TASK,
    UNABLE_TO_UPDATE_STATUS_FOR_EPIC_TASK,
    NON_EXISTING_TASK_ID,
    FAILED_TO_UPDATE_SUBTASK_NON_EXISTING_ID,
    FAILED_TO_DELETE_SUBTASK_NON_EXISTING_ID,
    ERROR_WRITING_FILE

}
