package HTTP;

public enum HttpFeedback {

    REQUEST_FOR_ALL_TASKS_DELETION_PROCESSED,

    REQUEST_FOR_NEW_TASK_CREATION_PROCESSED,

    REQUEST_FOR_TASK_DELETION_PROCESSED,

    REQUEST_FOR_NEW_SUBTASK_CREATION_PROCESSED,

    REQUEST_DOES_NOT_CONTAIN_REQUIRED_DATA,

    TASK_UPDATED,
    SUB_TASK_UPDATED;

}
